# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogAndReg', '0002_job_ownedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
