# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogAndReg', '0003_job_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Catagory',
            field=models.CharField(default='pineapple', max_length=255),
            preserve_default=False,
        ),
    ]
